/**
  * Action Types.
  */

export const TOGGLE_NAVIGATOR_CART_ICON = 'TOGGLE_NAVIGATOR_CART_ICON';
export const TOGGLE_PROGRESS_BAR = 'TOGGLE_PROGRESS_BAR';
export const SET_NAVIGATOR_BACKGROUND = 'SET_NAVIGATOR_BACKGROUND';
export const SET_NAVIGATOR_COLOR = 'SET_NAVIGATOR_COLOR';
export const SET_SEARCH_ENABLED = 'SET_SEARCH_ENABLED';
export const SET_SEARCH_DISABLED = 'SET_SEARCH_DISABLED';
export const SET_ICON_SHADOW_ENABLED = 'SET_ICON_SHADOW_ENABLED';
export const SET_ICON_SHADOW_DISABLED = 'SET_ICON_SHADOW_DISABLED';
export const SET_TITLE_ENABLED = 'SET_TITLE_ENABLED';
export const SET_TITLE_DISABLED = 'SET_TITLE_DISABLED';
export const SET_NAVIGATOR_DISABLED = 'SET_NAVIGATOR_DISABLED';
export const SET_NAVIGATOR_ENABLED = 'SET_NAVIGATOR_ENABLED';
