/**
  * Action types.
  */
export const TOGGLE_NAVIGATOR = 'TOGGLE_NAVIGATOR';
export const TOGGLE_NAVIGATOR_CART = 'TOGGLE_NAVIGATOR_CART';
export const TOGGLE_NAVIGATOR_SEARCH = 'TOGGLE_NAVIGATOR_SEARCH';
export const TOGGLE_NAVIGATOR_TITLE = 'TOGGLE_NAVIGATOR_TITLE';
export const TOGGLE_PROGRESSBAR = 'TOGGLE_PROGRESSBAR';
export const SET_NAVIGATOR_BACKGROUND = 'SET_NAVIGATOR_BACKGROUND';
export const SET_NAVIGATOR_COLOR = 'SET_NAVIGATOR_COLOR';

/**
  * Portal names.
  */
export const PORTAL_NAVIGATOR_BUTTON = 'NAVIGATOR_BUTTON';
