export const REQUEST_ORDER_DETAILS = 'REQUEST_ORDER_DETAILS';
export const RECEIVE_ORDER_DETAILS = 'RECEIVE_ORDER_DETAILS';
export const ERROR_ORDER_DETAILS = 'ERROR_ORDER_DETAILS';
export const ERROR_CANCEL_ORDER = 'ERROR_CANCEL_ORDER';

export const CLEAR_ORDERS = 'CLEAR_ORDERS';
