export const SEARCH_PATH = '/search/:searchPhrase';

export const SEARCH_SUGGESTIONS_LIFETIME = 86400000; // 24 hours in milliseconds

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const ERROR_SEARCH_RESULTS = 'ERROR_SEARCH_RESULTS';
export const REQUEST_SEARCH_SUGGESTIONS = 'REQUEST_SEARCH_SUGGESTIONS';
export const RECEIVE_SEARCH_SUGGESTIONS = 'RECEIVE_SEARCH_SUGGESTIONS';
