// FEATURES
const SEARCH = 'search';

// CONTENTS
const SUGGESTIONS = 'suggestions';
const SUGGESTION_ITEM = 'suggestion-item';
const SUGGESTION_ITEM_CONTENT = 'suggestion-item-content';

export const SEARCH_SUGGESTIONS = `${SEARCH}.${SUGGESTIONS}`;
export const SEARCH_SUGGESTION_ITEM = `${SEARCH}.${SUGGESTION_ITEM}`;
export const SEARCH_SUGGESTION_ITEM_CONTENT = `${SEARCH}.${SUGGESTION_ITEM_CONTENT}`;

export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';
