// PRODUCT REVIEWS LIST
export const REVIEWS_LIFETIME = 900000; // 15 minutes
export const REQUEST_REVIEWS = 'REQUEST_REVIEWS';
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';
export const ERROR_REVIEWS = 'ERROR_REVIEWS';

// PRODUCT REVIEWS
export const REQUEST_PRODUCT_REVIEWS = 'REQUEST_PRODUCT_REVIEWS';
export const RECEIVE_PRODUCT_REVIEWS = 'RECEIVE_PRODUCT_REVIEWS';
export const ERROR_PRODUCT_REVIEWS = 'ERROR_PRODUCT_REVIEWS';

// USER REVIEW
export const USER_REVIEW_LIFETIME = 300000; // 5 minutes
export const REQUEST_USER_REVIEW = 'REQUEST_USER_REVIEW';
export const RECEIVE_USER_REVIEW = 'RECEIVE_USER_REVIEW';
export const ERROR_USER_REVIEW = 'ERROR_USER_REVIEW';
export const FLUSH_USER_REVIEWS = 'FLUSH_USER_REVIEWS';

// SUBMIT REVIEW
export const REQUEST_SUBMIT_REVIEW = 'REQUEST_SUBMIT_REVIEW';
export const RECEIVE_SUBMIT_REVIEW = 'RECEIVE_SUBMIT_REVIEW';
export const ERROR_SUBMIT_REVIEW = 'ERROR_SUBMIT_REVIEW';
export const RESET_SUBMIT_REVIEW = 'RESET_SUBMIT_REVIEW';

/**
 * Max number of reviews shown
 * @type {number}
 */
export const REVIEW_PREVIEW_COUNT = 2;
