export const REQUEST_PRODUCT_REVIEW_SETTINGS = 'REQUEST_PRODUCT_REVIEW_SETTINGS';
export const RECEIVE_PRODUCT_REVIEW_SETTINGS = 'RECEIVE_PRODUCT_REVIEW_SETTINGS';
export const ERROR_PRODUCT_REVIEW_SETTINGS = 'ERROR_PRODUCT_REVIEW_SETTINGS';

export const REVIEW_SETTINGS_LIFETIME = 60 * 60 * 1000;

export const PAGINATION_TYPE_OFFSET = 'offset';
export const PAGINATION_TYPE_CURSOR = 'cursor';
