export const RECEIVE_MERCHANT_SETTINGS = 'RECEIVE_MERCHANT_SETTINGS';
export const MERCHANT_SETTINGS_LOCATION_BASED_SHOPPING_ENABLED = 'locationBasedShoppingEnabled';
export const MERCHANT_SETTINGS_SUBSTITUTION_PREFERENCES_ENABLED = 'enableSubstitutionPreferences';
export const MERCHANT_SETTINGS_CUSTOMER_ATTRIBUTES = 'customerAttributes';
export const MERCHANT_SETTINGS_FULFILLMENT_SCHEDULED_ENABLED = 'enableFulfillmentScheduling';
