export const SOFT_OPT_IN_SHOWN = 'SOFT_OPT_IN_SHOWN';
export const SOFT_OPT_IN_SELECTED = 'SOFT_OPT_IN_SELECTED';
export const HARD_OPT_IN_SHOWN = 'HARD_OPT_IN_SHOWN';
export const HARD_OPT_IN_SELECTED = 'HARD_OPT_IN_SELECTED';
