export const FILTER_PATH = '/filter';

export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const ERROR_FILTERS = 'ERROR_FILTERS';

export const ADD_ACTIVE_FILTERS = 'ADD_ACTIVE_FILTERS';
export const SLICE_ACTIVE_FILTERS = 'SLICE_ACTIVE_FILTERS';
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';

export const MERGE_TEMPORARY_FILTERS = 'MERGE_TEMPORARY_FILTERS';
export const SET_TEMPORARY_FILTERS = 'SET_TEMPORARY_FILTERS';
export const REMOVE_TEMPORARY_FILTER = 'REMOVE_TEMPORARY_FILTER';
