// MEDIA TYPES
export const MEDIA_TYPE_IMAGE = 'image';
export const MEDIA_TYPE_VIDEO = 'video';

// AVAILABILITY TYPES
export const AVAILABILITY_TYPE_AVAILABLE = 'available';
export const AVAILABILITY_TYPE_LIMITED_AVAILABILITY = 'limitedAvailability';
export const AVAILABILITY_TYPE_NOT_AVAILABLE = 'notAvailable';
export const AVAILABILITY_TYPE_CUSTOM_AVAILABILITY = 'customAvailability';
export const availabilityTypes = [
  AVAILABILITY_TYPE_AVAILABLE,
  AVAILABILITY_TYPE_LIMITED_AVAILABILITY,
  AVAILABILITY_TYPE_NOT_AVAILABLE,
  AVAILABILITY_TYPE_CUSTOM_AVAILABILITY,
];

export const PRODUCT_FULFILLMENT_METHOD_DIRECT_SHIP = 'directShip';
export const PRODUCT_FULFILLMENT_METHOD_IN_STORE_PICKUP = 'inStorePickup';
