export const checkoutOrder = {
  orderNumber: '1292',
  externalCode: null,
  type: 'standard',
  status: 'open',
  customerId: 'bed701a2-edf4-4d2c-b095-0d42e8feccd1',
  externalCustomerNumber: '20075992',
  expedited: false,
  localeCode: 'en-US',
  currencyCode: 'USD',
  taxExempt: false,
  primaryBillToAddressSequenceIndex: 0,
  primaryShipToAddressSequenceIndex: 1,
  subTotal: 71.69,
  discountAmount: 8,
  promoAmount: -21.51,
  taxAmount: 4.01,
  tax2Amount: 0,
  shippingSubTotal: 0,
  shippingDiscountAmount: 0,
  shippingPromoAmount: 0,
  shippingTotal: 2.9,
  total: 57.9,
  notes: '',
  specialInstructions: null,
  data: null,
  date: '2020-11-12T10:25:16.000Z',
  submitDate: '2020-11-12T10:25:36.000Z',
  completeDate: null,
  sourceIp: '52.28.146.255',
  domain: null,
  platform: 'engage',
  userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
  os: 'android',
  imported: false,
  taxSummary: [{ code: 'RG-US-TX-8', name: 'RG-US-TX-8', amount: 4.01 }],
  fulfillmentStatus: 'open',
  addressSequences: [
    {
      index: 0,
      type: 'billing',
      customerContactId: '5685b735-8c36-4088-a74a-845ff68182d6',
      firstName: 'John',
      middleName: null,
      lastName: 'Doe',
      companyName: '',
      address1: 'Test Street 8',
      address2: '',
      address3: null,
      address4: null,
      city: 'Test Town',
      region: 'AE',
      postalCode: '55555',
      country: 'US',
      phone: '+1555123456',
      fax: null,
      mobile: '+1555123456',
      emailAddress: 'test@example.com',
    },
    {
      index: 1,
      type: 'pickup',
      customerContactId: '5685b735-8c36-4088-a74a-845ff68182d6',
      firstName: 'John',
      middleName: null,
      lastName: 'Doe',
      companyName: '',
      address1: 'Test Street 8',
      address2: '',
      address3: null,
      address4: null,
      city: 'Test Town',
      region: 'AE',
      postalCode: '55555',
      country: 'US',
      phone: '+1555123456',
      fax: null,
      mobile: '+1555123456',
      emailAddress: 'test@example.com',
    },
  ],
  coupons: [],
  appliedPromotions: [
    {
      code: 'promoWithout2',
      name: 'Promo Without Coupon 30',
      model: 'simpleDiscount',
      coupon: null,
      impact: { conditions: null, automaticallyAddedToCart: false },
      status: 'active',
      target: 'order',
      endDate: null,
      discount: { type: 'percentage', amount: -30, absoluteAmount: -21.51 },
      couponSet: null,
      startDate: '2020-09-18T07:04:24.000Z',
      conditions: { $and: [] },
      description: '',
      limitConditions: null,
      promotionalText: '',
    },
  ],
  campaignAttribution: null,
  lineItems: [
    {
      code: '388fce7c-e2be-411c-b7da-8c6c7d415341',
      status: 'open',
      subStatus: null,
      quantity: 1,
      quantityChangeReason: null,
      currencyCode: 'USD',
      shippingAmount: 0,
      taxAmount: 1.79,
      tax2Amount: 0,
      taxExempt: false,
      discountAmount: 0,
      promoAmount: 0,
      overrideAmount: 0,
      extendedPrice: 0,
      price: 32,
      fulfillmentMethod: 'BOPIS',
      fulfillmentSlot: {
        id: '1442_2020-11-12',
        to: '16:00',
        date: '2020-11-12',
        from: '15:00',
        status: 'active',
        weekday: 'thu',
      },
      shipToAddressSequenceIndex: 0,
      product: {
        code: '24-MB04',
        name: 'Product One',
        unit: 'each',
        image: '',
        price: 32,
        options: [],
        salePrice: 32,
        currencyCode: 'USD',
        hasCatchWeight: false,
      },
      substitutionAllowed: true,
      replacedLineItemId: null,
      fulfillmentLocationCode: 'BU-CARS',
    },
    {
      code: 'a99abf92-f4ed-410d-abb6-2330590f9a85',
      status: 'open',
      subStatus: null,
      quantity: 2,
      quantityChangeReason: null,
      currencyCode: 'USD',
      shippingAmount: 0,
      taxAmount: 0.78,
      tax2Amount: 0,
      taxExempt: false,
      discountAmount: 0,
      promoAmount: 0,
      overrideAmount: 0,
      extendedPrice: 0,
      price: 14,
      fulfillmentMethod: 'BOPIS',
      fulfillmentSlot: {
        id: '1442_2020-11-12',
        to: '16:00',
        date: '2020-11-12',
        from: '15:00',
        status: 'active',
        weekday: 'thu',
      },
      shipToAddressSequenceIndex: 0,
      product: {
        code: '24-UG06',
        name: 'Product Two',
        unit: 'l',
        image: '',
        price: 7,
        options: [],
        salePrice: null,
        currencyCode: 'USD',
        hasCatchWeight: false,
      },
      substitutionAllowed: true,
      replacedLineItemId: null,
      fulfillmentLocationCode: 'BU-CARS',
    },
    {
      code: 'a03e4d68-0606-41cb-8e79-5864bfc486b3',
      status: 'open',
      subStatus: null,
      quantity: 1.25,
      quantityChangeReason: null,
      currencyCode: 'USD',
      shippingAmount: 0,
      taxAmount: 0.09,
      tax2Amount: 0,
      taxExempt: false,
      discountAmount: 0,
      promoAmount: 0,
      overrideAmount: 0,
      extendedPrice: 0,
      price: 1.69,
      fulfillmentMethod: 'BOPIS',
      fulfillmentSlot: {
        id: '1442_2020-11-12',
        to: '16:00',
        date: '2020-11-12',
        from: '15:00',
        status: 'active',
        weekday: 'thu',
      },
      shipToAddressSequenceIndex: 0,
      product: {
        code: 'FOOD-01',
        name: 'Product Three',
        unit: 'lb',
        image: '',
        price: 1.35,
        options: [],
        salePrice: null,
        currencyCode: 'USD',
        hasCatchWeight: true,
      },
      substitutionAllowed: true,
      replacedLineItemId: null,
      fulfillmentLocationCode: 'BU-CARS',
    },
  ],
  paymentTransactions: [
    {
      id: '2fe67d6a-c759-4331-afbe-dfb5c2500641',
      externalCode: 'pi_0HmczV7uuRMaCx6Gtwpdh0x2',
      type: 'order',
      status: 'authorized',
      authorizedAmount: 54.19,
      chargedAmount: null,
      paymentError: { code: null, message: null },
      paymentMethod: { code: 'stripe', type: 'cc', provider: 'stripe' },
      paymentInfo: { card: { type: 'visa', last4: '4242' }, type: 'cc' },
    },
  ],
  shopCode: 'shop_31381',
  fulfillmentGroups: [],
  customer: {
    id: 'bed701a2-edf4-4d2c-b095-0d42e8feccd1',
    externalCustomerNumber: '20075992',
    internalCustomerNumber: '220',
    status: 'active',
    firstName: 'John',
    middleName: '',
    lastName: 'Doe',
    emailAddress: 'text@example.com',
    externalUpdateDate: '2020-11-09T14:19:53.000Z',
    isAnonymous: false,
    taxExempt: false,
    taxClass: null,
    contacts: [
      {
        id: '5685b735-8c36-4088-a74a-845ff68182d6',
        externalContactCode: null,
        status: 'active',
        firstName: 'John',
        middleName: null,
        lastName: 'Doe',
        companyName: '',
        address1: 'Test Street 8',
        address2: '',
        address3: null,
        address4: null,
        city: 'Test Town',
        region: 'AE',
        postalCode: '55555',
        country: 'US',
        phone: '+1555123456',
        fax: null,
        mobile: '+1555123456',
        emailAddress: 'text@example.com',
        isDefaultBilling: true,
        isDefaultShipping: false,
        externalUpdateDate: '2020-10-21T14:15:00.000Z',
      },
      {
        id: '2a277f9f-f66b-4a6c-bf7f-2ec9b026f540',
        externalContactCode: null,
        status: 'active',
        firstName: 'John',
        middleName: null,
        lastName: 'Doe',
        companyName: '',
        address1: 'Test Street 8',
        address2: '',
        address3: null,
        address4: null,
        city: 'Test Town',
        region: 'AE',
        postalCode: '55555',
        country: 'US',
        phone: '',
        fax: null,
        mobile: '',
        emailAddress: 'text@example.com',
        isDefaultBilling: false,
        isDefaultShipping: true,
        externalUpdateDate: '2020-04-07T10:41:49.000Z',
      },
    ],
    attributes: [
      {
        name: 'Player character level',
        code: 'charLvl',
        value: { code: '14', name: '14' },
      },
      { name: 'Required free text field', code: 'reqText', value: '1235' },
      { name: 'Goes by school bus', code: 'schoolbus_bool', value: true },
      { name: 'Years playing', code: 'yearsPlaying', value: 32.123 },
      {
        name: 'Date (this time really at the end)',
        code: 'zzzdateFieldEnd',
        value: '2020-11-09',
      },
    ],
    settings: {
      marketingOptIn: true,
      defaultLocale: 'en-US',
      defaultCurrency: 'USD',
      defaultLocationCode: null,
      communicationPreferences: ['sms', 'push'],
    },
  },
};
