export const FILTER_PATH = '/filter';

export const SET_FILTER_HASH = 'SET_FILTER_HASH';
export const SET_FILTER_INDEX = 'SET_FILTER_INDEX';

export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const ERROR_FILTERS = 'ERROR_FILTERS';

export const ADD_ACTIVE_FILTERS = 'ADD_ACTIVE_FILTERS';
export const REMOVE_ACTIVE_FILTERS = 'REMOVE_ACTIVE_FILTERS';
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';
export const RESET_ACTIVE_FILTERS = 'RESET_ACTIVE_FILTERS';

export const MERGE_TEMPORARY_FILTERS = 'MERGE_TEMPORARY_FILTERS';
export const SET_TEMPORARY_FILTERS = 'SET_TEMPORARY_FILTERS';
export const REMOVE_TEMPORARY_FILTER = 'REMOVE_TEMPORARY_FILTER';

export const FILTER_TYPE_SINGLE_SELECT = 'single_select';
export const FILTER_TYPE_MULTISELECT = 'multiselect';
export const FILTER_TYPE_RANGE = 'range';

