export const CONNECTIVITY_NETWORK_UNKNOWN = 'UNKNOWN';
export const CONNECTIVITY_TYPE_UNKNOWN = 'UNKNOWN';
export const CONNECTIVITY_TYPE_WIFI = 'WIFI';
export const CONNECTIVITY_TYPE_4G = '4G';
export const CONNECTIVITY_TYPE_3G = '3G';
export const CONNECTIVITY_TYPE_2G = '2G';
