export const APP_PLATFORM = 'APP_PLATFORM';
export const RESET_APP_REDUCERS = 'RESET_APP_REDUCERS';
export const DEFAULT_PRODUCTS_FETCH_PARAMS = 'DEFAULT_PRODUCTS_FETCH_PARAMS';
export const TAB_BAR_PATTERNS_BLACK_LIST = 'TAB_BAR_PATTERNS_BLACK_LIST';
export const CONFIGURATION_COLLECTION_KEY_BASE_URL = 'CONFIGURATION_COLLECTION_KEY_BASE_URL';
export const PIPELINES = 'PIPELINES';
export const IS_CONNECT_EXTENSION_ATTACHED = 'IS_CONNECT_EXTENSION_ATTACHED';
