export const APP_PLATFORM = Symbol('APP_PLATFORM');
export const RESET_APP_REDUCERS = Symbol('RESET_APP_REDUCERS');
export const DEFAULT_PRODUCTS_FETCH_PARAMS = Symbol('DEFAULT_PRODUCTS_FETCH_PARAMS');
export const TAB_BAR_PATTERNS_BLACK_LIST = Symbol('TAB_BAR_PATTERNS_BLACK_LIST');
export const CONFIGURATION_COLLECTION_KEY_BASE_URL = 'CONFIGURATION_COLLECTION_KEY_BASE_URL';
export const PIPELINES = Symbol('PIPELINES');
export const IS_CONNECT_EXTENSION_ATTACHED = Symbol('IS_CONNECT_EXTENSION_ATTACHED');
