/**
 * Runtime layout dimensions exposed as global CSS variables.
 *
 * These are NOT design tokens and are not generated by the theme's CSS-variable pipeline.
 * The underlying variables are measured/updated at runtime by other parts of the app:
 * - `--app-bar-height` is set by the AppBar components (measured height).
 * - `--footer-height` is set by the Footer helpers (measured height).
 * - `--safe-area-inset-*` are set by `updatePageInsets` based on the device page insets.
 *
 * This node only maps theme properties to those existing variables (`var(--...)`), so consumers
 * can read `theme.layout.*` instead of hardcoding the variable names.
 */
export interface SafeArea {
  top: string;
  bottom: string;
  left: string;
  right: string;
}

export interface Layout {
  /** Live height of the app bar (`--app-bar-height`). */
  appBarHeight: string;
  /** Live height of the footer (`--footer-height`). */
  footerHeight: string;
  /** Device safe-area insets (`--safe-area-inset-*`). */
  safeArea: SafeArea;
}

const layout: Layout = {
  appBarHeight: 'var(--app-bar-height)',
  footerHeight: 'var(--footer-height)',
  safeArea: {
    top: 'var(--safe-area-inset-top)',
    bottom: 'var(--safe-area-inset-bottom)',
    left: 'var(--safe-area-inset-left)',
    right: 'var(--safe-area-inset-right)',
  },
};

export default layout;
