/**
 * Runtime layout dimensions exposed as global CSS variables.
 *
 * These are NOT design tokens and are not generated by the theme's CSS-variable pipeline.
 * The `--safe-area-inset-*` variables are set at runtime by `updatePageInsets` based on the
 * device page insets.
 *
 * This node only maps theme properties to those existing variables (`var(--...)`), so consumers
 * can read `theme.layout.*` instead of hardcoding the variable names.
 */
export interface SafeArea {
  top: string;
  bottom: string;
  left: string;
  right: string;
}

export interface Layout {
  /** Device safe-area insets (`--safe-area-inset-*`). */
  safeArea: SafeArea;
}

const layout: Layout = {
  safeArea: {
    top: 'var(--safe-area-inset-top)',
    bottom: 'var(--safe-area-inset-bottom)',
    left: 'var(--safe-area-inset-left)',
    right: 'var(--safe-area-inset-right)',
  },
};

export default layout;
