export const PUSH_OPT_IN_INCREASE_APP_START_COUNT = 'PUSH_OPT_IN_INCREASE_APP_START_COUNT';
export const PUSH_OPT_IN_RESET_APP_START_COUNT = 'PUSH_OPT_IN_RESET_APP_START_COUNT';
export const PUSH_OPT_IN_RESET_APP_START_STATE = 'PUSH_OPT_IN_RESET_APP_START_STATE';

export const PUSH_OPT_IN_INCREASE_ORDERS_PLACED_COUNT = 'PUSH_OPT_IN_INCREASE_ORDERS_PLACED_COUNT';
export const PUSH_OPT_IN_RESET_ORDERS_PLACED_COUNT = 'PUSH_OPT_IN_RESET_ORDERS_PLACED_COUNT';
export const PUSH_OPT_IN_RESET_ORDERS_PLACED_STATE = 'PUSH_OPT_IN_RESET_ORDERS_PLACED_STATE';

export const PUSH_OPT_IN_SET_LAST_POPUP_TIMESTAMP = 'PUSH_OPT_IN_SET_LAST_POPUP_TIMESTAMP';

export const PUSH_OPT_IN_INCREASE_REJECTION_COUNT = 'PUSH_OPT_IN_INCREASE_REJECTION_COUNT';

export const PUSH_OPT_IN_OPT_IN_POSTPONED = 'PUSH_OPT_IN_OPT_IN_POSTPONED';
