// @flow
// LOCATIONS
export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS';
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS';
export const ERROR_LOCATIONS = 'ERROR_LOCATIONS';

// USER
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const STORE_FORM_INPUT = 'STORE_FORM_INPUT';
export const STORE_FULFILLMENT_METHOD = 'STORE_FULFILLMENT_METHOD';
export const STORE_SEARCH_QUERY = 'STORE_SEARCH_QUERY';

// PRODUCTION LOCATIONS
export const REQUEST_PRODUCT_LOCATIONS = 'REQUEST_PRODUCT_LOCATIONS';
export const RECEIVE_PRODUCT_LOCATIONS = 'RECEIVE_PRODUCT_LOCATIONS';
export const ERROR_PRODUCT_LOCATIONS = 'ERROR_PRODUCT_LOCATIONS';

// SUBMIT RESERVATION
export const SUBMIT_RESERVATION_REQUEST = 'SUBMIT_RESERVATION_REQUEST';
export const SUBMIT_RESERVATION_SUCCESS = 'SUBMIT_RESERVATION_SUCCESS';
export const SUBMIT_RESERVATION_ERROR = 'SUBMIT_RESERVATION_ERROR';
