// PRODUCTION LOCATIONS
export const REQUEST_PRODUCT_LOCATIONS = 'REQUEST_PRODUCT_LOCATIONS';
export const RECEIVE_PRODUCT_LOCATIONS = 'RECEIVE_PRODUCT_LOCATIONS';
export const ERROR_PRODUCT_LOCATIONS = 'ERROR_PRODUCT_LOCATIONS';

// SUBMIT RESERVATION
export const SUBMIT_RESERVATION_REQUEST = 'SUBMIT_RESERVATION_REQUEST';
export const SUBMIT_RESERVATION_SUCCESS = 'SUBMIT_RESERVATION_SUCCESS';
export const SUBMIT_RESERVATION_ERROR = 'SUBMIT_RESERVATION_ERROR';
