// @flow
// ACTION TYPES
export {
  REQUEST_LOCATIONS,
  RECEIVE_LOCATIONS,
  ERROR_LOCATIONS,
  SELECT_LOCATION,
  STORE_FORM_INPUT,
  STORE_FULFILLMENT_METHOD,
  SET_USER_SEARCH_COUNTRY_CODE,
  SET_USER_SEARCH_POSTAL_CODE,
  REQUEST_PRODUCT_LOCATIONS,
  RECEIVE_PRODUCT_LOCATIONS,
  ERROR_PRODUCT_LOCATIONS,
  SUBMIT_RESERVATION_REQUEST,
  SUBMIT_RESERVATION_SUCCESS,
  SUBMIT_RESERVATION_ERROR,
} from './ActionTypes';

// PIPELINES
export {
  SHOPGATE_STOREFRONT_GET_PRODUCT_LOCATIONS,
  SHOPGATE_STOREFRONT_CREATE_ORDER,
  SHOPGATE_STOREFRONT_GET_LOCATIONS,
} from './Pipelines';

// PORTALS
export {
  PRODUCT_FULFILLMENT_SELECTOR,
  PRODUCT_LOCATION_STOCK_INFO,
} from './Portals';

export const DIRECT_SHIP = 'directShip';
export const DIRECT_SHIP_LABEL = 'locations.fulfillment.direct_ship';
export const IN_STORE_PICKUP = 'inStorePickup';
export const IN_STORE_PICKUP_LABEL = 'locations.fulfillment.pick_up_in_store';
export const ROPIS = 'ROPIS';
export const BOPIS = 'BOPIS';
export const QUICK_RESERVE = 'quickReserve';
export const MULTI_LINE_RESERVE = 'multiLineReserve';

export const DEFAULT_ROPE_FULFILLMENT_METHOD = 'defaultRopeFulfillmentMethod';

export {
  STAGE_SELECT_STORE,
  STAGE_RESERVE_FORM,
  STAGE_RESPONSE_SUCCESS,
  STAGE_RESPONSE_ERROR,
  STAGE_FULFILLMENT_METHOD,
} from './Stages';
