// @flow
// ACTION TYPES
export {
  REQUEST_LOCATIONS,
  RECEIVE_LOCATIONS,
  ERROR_LOCATIONS,
  SELECT_LOCATION,
  STORE_FORM_INPUT,
  STORE_FULFILLMENT_METHOD,
  STORE_SEARCH_QUERY,
  REQUEST_PRODUCT_LOCATIONS,
  RECEIVE_PRODUCT_LOCATIONS,
  ERROR_PRODUCT_LOCATIONS,
  SUBMIT_RESERVATION_REQUEST,
  SUBMIT_RESERVATION_SUCCESS,
  SUBMIT_RESERVATION_ERROR,
} from './ActionTypes';

// PIPELINES
export {
  SHOPGATE_STOREFRONT_GET_PRODUCT_LOCATIONS,
  SHOPGATE_STOREFRONT_CREATE_ORDER,
  SHOPGATE_STOREFRONT_GET_LOCATIONS,
  SHOPGATE_STOREFRONT_GET_CART,
  SHOPGATE_STOREFRONT_UPDATE_CART,
} from './Pipelines';

// PORTALS
export {
  PRODUCT_FULFILLMENT_SELECTOR_BEFORE,
  PRODUCT_FULFILLMENT_SELECTOR,
  PRODUCT_FULFILLMENT_SELECTOR_AFTER,
  PRODUCT_LOCATION_STOCK_INFO_BEFORE,
  PRODUCT_LOCATION_STOCK_INFO,
  PRODUCT_LOCATION_STOCK_INFO_AFTER,
} from './Portals';

export const PRODUCT_FULFILLMENT_METHOD_DIRECT_SHIP = 'directShip';
export const PRODUCT_FULFILLMENT_METHOD_IN_STORE_PICKUP = 'inStorePickup';
export const PRODUCT_FULFILLMENT_METHOD_ROPIS = 'ROPIS';

export const FULFILLMENT_PATH_QUICK_RESERVE = 'quickReserve';
export const FULFILLMENT_PATH_MULTI_LINE_RESERVE = 'multiLineReserve';

export {
  STAGE_SELECT_STORE,
  STAGE_RESERVE_FORM,
  STAGE_RESPONSE_SUCCESS,
  STAGE_RESPONSE_ERROR,
  STAGE_FULFILLMENT_METHOD,
} from './Stages';
