export const DIALOG_TEXT_MESSAGE = 'DIALOG_TEXT_MESSAGE';
export const DIALOG_HTML_CONTENT = 'DIALOG_HTML_CONTENT';
export const MODAL_VARIANT_SELECT = 'MODAL_VARIANT_SELECT';

export const MODAL_ACTION_TYPE_NORMAL = 'normal';
export const MODAL_ACTION_TYPE_PRIMARY = 'primary';
export const MODAL_ACTION_TYPE_DANGER = 'danger';
