export const REQUEST_ORDER_HISTORY = 'REQUEST_ORDER_HISTORY';
export const RECEIVE_ORDER_HISTORY = 'RECEIVE_ORDER_HISTORY';
export const ERROR_ORDER_HISTORY = 'ERROR_ORDER_HISTORY';

export const FETCH_CUSTOMER_CONTACTS = 'FETCH_CUSTOMER_CONTACTS';
export const FETCH_CUSTOMER_CONTACTS_SUCCESS = 'FETCH_CUSTOMER_CONTACTS_SUCCESS';
export const FETCH_CUSTOMER_CONTACTS_ERROR = 'FETCH_CUSTOMER_CONTACTS_ERROR';

export const FETCH_CUSTOMER = 'FETCH_CUSTOMER_CONTACTS';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER_CONTACTS';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';

export const UPDATE_CUSTOMER_CONTACT = 'UPDATE_CUSTOMER_CONTACT';
export const UPDATE_CUSTOMER_CONTACT_SUCCESS = 'UPDATE_CUSTOMER_CONTACT_SUCCESS';
export const UPDATE_CUSTOMER_CONTACT_ERROR = 'UPDATE_CUSTOMER_CONTACT_ERROR';

export const ADD_CUSTOMER_CONTACT = 'ADD_CUSTOMER_CONTACT';
export const ADD_CUSTOMER_CONTACT_SUCCESS = 'ADD_CUSTOMER_CONTACT_SUCCESS';
export const ADD_CUSTOMER_CONTACT_ERROR = 'ADD_CUSTOMER_CONTACT_ERROR';

export const DELETE_CUSTOMER_CONTACT = 'DELETE_CUSTOMER_CONTACT';
export const DELETE_CUSTOMER_CONTACT_SUCCESS = 'DELETE_CUSTOMER_CONTACT_SUCCESS';
export const DELETE_CUSTOMER_CONTACT_ERROR = 'DELETE_CUSTOMER_CONTACT_ERROR';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';
