export const INCREASE_APP_START_COUNT = 'INCREASE_APP_START_COUNT';
export const RESET_APP_START_COUNT = 'RESET_APP_START_COUNT';
export const RESET_APP_START_STATE = 'RESET_APP_START_STATE';

export const INCREASE_ORDERS_PLACED_COUNT = 'INCREASE_ORDERS_PLACED_COUNT';
export const RESET_ORDERS_PLACED_COUNT = 'RESET_ORDERS_PLACED_COUNT';
export const RESET_ORDERS_PLACED_STATE = 'RESET_ORDERS_PLACED_STATE';

export const INCREASE_TIMER_REPEATS = 'INCREASE_TIMER_REPEATS';
export const SET_TIMER_START_TIME = 'SET_TIMER_START_TIME';

export const SET_LAST_POPUP_TIMESTAMP = 'SET_LAST_POPUP_TIMESTAMP';

export const INCREASE_REJECTION_COUNT = 'INCREASE_REJECTION_COUNT';
export const SET_ALREADY_RATED = 'SET_ALREADY_RATED';

// currently the timespan is set to a day
export const TIMER_TIMESPAN = 1000 * 60 * 60 * 24;
