export const RESET_RATE_STATE = 'RESET_RATE_STATE';

export const INCREASE_APP_START_COUNT = 'INCREASE_APP_START_COUNT';
export const RESET_APP_START_COUNT = 'RESET_APP_START_COUNT';
export const RESET_APP_START_STATE = 'RESET_APP_START';

export const INCREASE_ORDERS_PLACED_COUNT = 'INCREASE_TIMER_REPEATS';
export const RESET_ORDERS_PLACED_COUNT = 'RESET_ORDERS_PLACED_COUNT';
export const RESET_ORDERS_PLACED_STATE = 'RESET_ORDERS_PLACED';

export const INCREASE_TIMER_REPEATS = 'INCREASE_TIMER_REPEATS';
export const SET_TIMER_START_TIME = 'SET_TIMER_START_TIME';

export const SET_LAST_POPUP_TIMESTAMP = 'SET_LAST_POPUP_TIMESTAMP';

export const TIMER_TIMESPAN = 1000 * 60 * 60;

/**
 * @typedef {"appStarts" | "ordersPlaced" | "timer"} RULE_TYPES
 */

export const RULE_APP_STARTS = 'appStarts';
export const RULE_ORDERS_PLACED = 'ordersPlaced';
export const RULE_TIMER = 'timer';
