export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const VALIDATION_ERRORS_REGISTRATION = 'VALIDATION_ERRORS_REGISTRATION';
