export {
  SHOPGATE_USER_REGISTER,
} from './pipelines';

export {
  REQUEST_REGISTRATION,
  SUCCESS_REGISTRATION,
  ERROR_REGISTRATION,
  VALIDATION_ERRORS_REGISTRATION,
} from './actionTypes';

export const MARKETING_OPT_IN_DEFAULT = true;
