export const INCREMENT_ACTION_COUNT = 'INCREMENT_ACTION_COUNT';
export const DECREMENT_ACTION_COUNT = 'DECREMENT_ACTION_COUNT';
export const RESET_ACTION_COUNT = 'RESET_ACTION_COUNT';
export const SHOW_ADD_TO_CART_BAR = 'SHOW_ADD_TO_CART_BAR';
export const HIDE_ADD_TO_CART_BAR = 'HIDE_ADD_TO_CART_BAR';
