export const SHOW_COOKIE_CONSENT_MODAL = 'SHOW_COOKIE_CONSENT_MODAL';
export const HIDE_COOKIE_CONSENT_MODAL = 'HIDE_COOKIE_CONSENT_MODAL';

export const ACCEPT_SELECTED_COOKIES = 'ACCEPT_SELECTED_COOKIES';
export const ACCEPT_ALL_COOKIES = 'ACCEPT_ALL_COOKIES';
export const ACCEPT_REQUIRED_COOKIES = 'ACCEPT_REQUIRED_COOKIES';

export const COOKIE_CONSENT_PATTERN = '/cookie-consent';

