export const INITIALIZE_CHECKOUT = 'INITIALIZE_CHECKOUT';
export const INITIALIZE_CHECKOUT_SUCCESS = 'INITIALIZE_CHECKOUT_SUCCESS';
export const INITIALIZE_CHECKOUT_ERROR = 'INITIALIZE_CHECKOUT_ERROR';

export const FETCH_CHECKOUT_ORDER = 'FETCH_CHECKOUT_ORDER';
export const FETCH_CHECKOUT_ORDER_SUCCESS = 'FETCH_CHECKOUT_ORDER_SUCCESS';
export const FETCH_CHECKOUT_ORDER_ERROR = 'FETCH_CHECKOUT_ORDER_ERROR';

export const FETCH_PAYMENT_METHODS = 'FETCH_PAYMENT_METHODS';
export const FETCH_PAYMENT_METHODS_SUCCESS = 'FETCH_PAYMENT_METHODS_SUCCESS';
export const FETCH_PAYMENT_METHODS_ERROR = 'FETCH_PAYMENT_METHODS_ERROR';

export const UPDATE_CHECKOUT_ORDER = 'UPDATE_CHECKOUT_ORDER';
export const UPDATE_CHECKOUT_ORDER_SUCCESS = 'UPDATE_CHECKOUT_ORDER_SUCCESS';
export const UPDATE_CHECKOUT_ORDER_ERROR = 'UPDATE_CHECKOUT_ORDER_ERROR';
