export const REQUEST_SHOPIFY_LOGIN = 'REQUEST_SHOPIFY_LOGIN';
export const SUCCESS_SHOPIFY_LOGIN = 'SUCCESS_SHOPIFY_LOGIN';
export const ERROR_SHOPIFY_LOGIN = 'ERROR_SHOPIFY_LOGIN';

export const REQUEST_SHOPIFY_LOGOUT = 'REQUEST_SHOPIFY_LOGOUT';
export const SUCCESS_SHOPIFY_LOGOUT = 'SUCCESS_SHOPIFY_LOGOUT';
export const ERROR_SHOPIFY_LOGOUT = 'ERROR_SHOPIFY_LOGOUT';

export const WEBCHECKOUT_REGISTER_REDIRECT = 'WEBCHECKOUT_REGISTER_REDIRECT';
