export const BACK_IN_STOCK_PATTERN = '/back-in-stock';

export const FETCH_BACK_IN_STOCK_REMINDERS = 'FETCH_BACK_IN_STOCK_REMINDERS';
export const FETCH_BACK_IN_STOCK_REMINDERS_SUCCESS = 'FETCH_BACK_IN_STOCK_REMINDERS_SUCCESS';
export const FETCH_BACK_IN_STOCK_REMINDERS_ERROR = 'FETCH_BACK_IN_STOCK_REMINDERS_ERROR';
