export const BACK_IN_STOCK_PATTERN = '/back-in-stock';

export const FETCH_BACK_IN_STOCK_REMINDERS = 'FETCH_BACK_IN_STOCK_REMINDERS';
export const FETCH_BACK_IN_STOCK_REMINDERS_SUCCESS = 'FETCH_BACK_IN_STOCK_REMINDERS_SUCCESS';
export const FETCH_BACK_IN_STOCK_REMINDERS_ERROR = 'FETCH_BACK_IN_STOCK_REMINDERS_ERROR';

export const ADD_BACK_IN_STOCK_REMINDERS = 'ADD_BACK_IN_STOCK_REMINDERS';
export const ADD_BACK_IN_STOCK_REMINDERS_SUCCESS = 'ADD_BACK_IN_STOCK_REMINDERS_SUCCESS';
export const ADD_BACK_IN_STOCK_REMINDERS_ERROR = 'ADD_BACK_IN_STOCK_REMINDERS_ERROR';

export const REMOVE_BACK_IN_STOCK_REMINDERS = 'REMOVE_BACK_IN_STOCK_REMINDERS';
export const REMOVE_BACK_IN_STOCK_REMINDERS_SUCCESS = 'REMOVE_BACK_IN_STOCK_REMINDERS_SUCCESS';
export const REMOVE_BACK_IN_STOCK_REMINDERS_ERROR = 'REMOVE_BACK_IN_STOCK_REMINDERS_ERROR';
