export const SHOW_COOKIE_CONSENT_MODAL = 'SHOW_COOKIE_CONSENT_MODAL';
export const HIDE_COOKIE_CONSENT_MODAL = 'HIDE_COOKIE_CONSENT_MODAL';

export const UPDATE_COOKIE_CONSENT = 'UPDATE_COOKIE_CONSENT';

export const COOKIE_CONSENT_HANDLED = 'COOKIE_CONSENT_HANDLED';

export const PRIVACY_SETTINGS_PATTERN = '/privacy-settings';
